FIX: user_data is assigned when the pointer is not initialized.
RT-Thread-packages/mpu-6xxx pull request #23
Opened 2022-01-09 16:39 UTC by iubiu

DETAIL: 当不注册 sensor device 时，会导致空指针错误
JIRA: N/A
TEST: pass

2022-01-10 08:38 UTC, Guozhanxin commented
什么时候会不注册 sensor device 啊

2022-01-10 17:54 UTC, iubiu commented
没有使能 PKG_USING_MPU6XXX_ACCE / PKG_USING_MPU6XXX_GYRO / PKG_USING_MPU6XXX_MAG 任意一个宏都会产生空指针赋值

2022-01-11 01:44 UTC, Guozhanxin commented on src/sensor_inven_mpu6xxx.c
> +        sensor_acce->parent.user_data = mpu_dev_temp;
在rt_hw_sensor_register 里会对这个变量进行赋值的，这里的赋值就被充掉了。所以最好是以传参的方式，传进去。把下面那一行最后一个参数 RT_NULL 改为 mpu_dev_temp。

![image](https://user-images.githubusercontent.com/25633294/148866524-4fe20fd9-0555-4685-bf65-d8e3fec37e35.png)

2022-01-11 01:44 UTC, Guozhanxin requested changes
再完善一下吧

2022-01-11 16:43 UTC, closed without merging

2022-01-11 16:46 UTC, bzrobotics commented
已按要求整改，请 review #24